### ISSUE TITLE
Dependency Conflict 

### ISSUE THREAD

**Issue by jonatanmenghetti** [camptocamp/puppet-mcollective#52]
Hi! 
When try install camptocamp-mcollective module, show dependency conflict: 
puppet module install camptocamp-mcollective
Notice: Preparing to install into /etc/puppet/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Error: Could not install module 'camptocamp-mcollective' (latest)
  Dependency 'camptocamp-ruby' (v1.1.1) would overwrite /etc/puppet/modules/ruby
    Currently, 'puppetlabs-ruby' (v0.4.0) is installed to that directory
    Use `puppet module install --ignore-dependencies` to install only this module

But puppetlabs-ruby is used by another modules and can't uninstall this module, if I try download from github, but can't search class and puppet generate new error:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find class ::ruby::gems for puppet.unimestre.com on node puppet.xxxx.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Tnks.

**Comment by mcanevet** [comment]
@jonatanmenghetti we can't easily fix this issue as it a general problem of puppet's lack of namespace separation.
